# Generated by Django 5.0.1 on 2024-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_for_Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojas',
            name='Pooja_picture',
            field=models.ImageField(null=True, upload_to='Pooja_picture'),
        ),
    ]
