# Generated by Django 4.2.11 on 2024-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_for_Project', '0005_remove_customer_user_remove_orderplaced_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='static/Pooja_picture'),
        ),
    ]
