# Generated by Django 4.2.11 on 2024-04-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_for_Project', '0007_alter_poojas_pooja_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojas',
            name='Pooja_picture',
            field=models.ImageField(null=True, upload_to='API_for_Project/static/Pooja_picture'),
        ),
    ]
