# Generated by Django 4.2.11 on 2024-04-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_for_Project', '0009_items_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('OP', 'Occasional'), ('FP', 'Festival'), ('HP', 'Homas')], max_length=2)),
                ('product_image', models.ImageField(upload_to='API_for_Project/static/Pooja_picture')),
                ('Items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_for_Project.dict')),
            ],
        ),
    ]
