# Generated by Django 4.2.11 on 2024-04-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_for_Project', '0011_remove_products_items_products_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='cxategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Category_image', models.ImageField(upload_to='API_for_Project/static/Pooja_picture')),
            ],
        ),
    ]
