# Generated by Django 4.2.11 on 2024-04-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_for_Project', '0012_cxategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxategories',
            name='classified',
            field=models.CharField(choices=[('CR', 'Occasional'), ('ML', 'Festival'), ('MS', 'Homas')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Occasional'), ('ML', 'Festival'), ('MS', 'Homas')], max_length=2),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('CR', 'Occasional'), ('ML', 'Festival'), ('MS', 'Homas')], max_length=2),
        ),
    ]
