# Generated by Django 4.2.11 on 2024-04-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_for_Project', '0013_cxategories_classified_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poojas',
            name='Pooja_picture',
            field=models.ImageField(null=True, upload_to='static/Pooja_picture'),
        ),
    ]
