# Generated by Django 4.2.11 on 2024-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_for_Project', '0014_alter_poojas_pooja_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cxategories',
            name='Category_image',
            field=models.ImageField(upload_to='static/Pooja_picture'),
        ),
    ]
